client: condor
sampling:
  start_date: 20001231
  end_date: 20010106
metrics:
  metric:
    - baseline: '20170920'
      releases:
        - ComcastSRS-2.18.0
        - ComcastSRS-2.17.0
        - ComcastSRS-2.16.8
        - ComcastSRS-2.15.0
        - ComcastSRS-2.14.1
        - ComcastSRS-2.9.2
        - ComcastSRS-2.8.3
        - ComcastSRS-2.7.5
        - ComcastSRS-2.6.4
  output_dir: /Users/lisa/ASAPPinc/data
report:
