client: condor
metrics:
  metric:
    - baseline: 20170920
      releases:
        - release: ComcastSRS-2.19.0
        - release: ComcastSRS-2.18.0
        - release: ComcastSRS-2.17.0
        - release: ComcastSRS-2.16.8
        - release: ComcastSRS-2.15.0
        - release: ComcastSRS-2.14.1
        - release: ComcastSRS-2.9.2
        - release: ComcastSRS-2.8.3
        - release: ComcastSRS-2.7.5
        - release: ComcastSRS-2.6.4
  output_dir: /Users/lisa/ASAPPinc/data
report:
